name: Arikkusan-Fallen_Kingdoms
version: '${project.version}'
main: fr.arikkusan.main
api-version: 1.19
authors: [ Arikkusan ]
commands:
  FkTeam:
    description: Allow player to manage Teams
    usage: /<command>
    aliases: [fkt]
  CustomName:
    description: Allow player to set their own Custom name
    usage: /<command>
    aliases: [cst]
  FallenKingdoms:
    description: Run fallen Kingdoms logic
    usage: /<command>
    aliases: [fk, game]
  gm:
    description: Put the user in gm1 / gm0
    usage: /<command>
  teamName:
    description: Allow changing the team name
    usage: /<command>
    aliases: [tn]
  teamCenter:
    description: Center specific bases
    usage: /<command>
    aliases: [tc]
  base:
    description: Give compass pointing to your base
    usage: /<command>
    aliases: [b]