name: Arikkusan-Fallen_Kingdoms
version: '${project.version}'
main: fr.arikkusan.fallenkingdoms
api-version: 1.19
authors: [ Arikkusan ]
commands:
  FkTeam:
    description: Allow player to manage Teams
    usage: /<command>
    aliases: [fkt]
    permission: not op
  CustomName:
    description: Allow player to set their own Custom name
    usage: /<command>
    aliases: [cst]
    permission: not op
  FallenKingdom:
    description: Run fallen Kingdoms logic
    usage: /<command>
    aliases: [fk, game]
    permission: not op
